#! /bin/bash

# TryHackMe King of the Hill - Network application port changer
# Change the port number of running network services
# Ryan McMillan 2022

echo -e "\u001b[38;5;11m"
echo " ██▓███   ▒█████   ██▀███  ▄▄▄█████▓ ▄▄▄       ██▓    "
echo "▓██░  ██▒▒██▒  ██▒▓██ ▒ ██▒▓  ██▒ ▓▒▒████▄    ▓██▒    "
echo "▓██░ ██▓▒▒██░  ██▒▓██ ░▄█ ▒▒ ▓██░ ▒░▒██  ▀█▄  ▒██░    "
echo "▒██▄█▓▒ ▒▒██   ██░▒██▀▀█▄  ░ ▓██▓ ░ ░██▄▄▄▄██ ▒██░    "
echo "▒██▒ ░  ░░ ████▓▒░░██▓ ▒██▒  ▒██▒ ░  ▓█   ▓██▒░██████▒"
echo "▒▓▒░ ░  ░░ ▒░▒░▒░ ░ ▒▓ ░▒▓░  ▒ ░░    ▒▒   ▓▒█░░ ▒░▓  ░"
echo "░▒ ░       ░ ▒ ▒░   ░▒ ░ ▒░    ░      ▒   ▒▒ ░░ ░ ▒  ░"
echo "░░       ░ ░ ░ ▒    ░░   ░   ░        ░   ▒     ░ ░   "
echo "             ░ ░     ░                    ░  ░    ░  ░"
echo
echo "Change the running network application ports forcing other users to re-enumerate the box in TryHackMe King of the Hill or Attack/Defense style CTFs"
echo "Ryan McMillan 2022"
echo -e "\033[0m"
echo
